openapi: 3.2.0
info:
  title: Partners API
  version: v1
servers:
- url: https://cubi-sandbox-api.customersbank.com/partners/v1
tags:
- name: Partners
paths:
  /:
    get:
      tags:
      - Partners
      summary: / - GET
      operationId: get
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerDto'
              example:
                id: string
                name: string
                isFrozen: true
                apiProducts:
                - id: string
                  name: string
                  isEnabled: true
                isApiCredentialsEnabled: true
                isAddressBookEnabled: true
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerDto'
              example:
                id: string
                name: string
                isFrozen: true
                apiProducts:
                - id: string
                  name: string
                  isEnabled: true
                isApiCredentialsEnabled: true
                isAddressBookEnabled: true
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /credentials:
    get:
      tags:
      - Partners
      summary: /credentials - GET
      operationId: get-credentials
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerCredentialDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerCredentialDto'
              example:
                keyId: string
                displayName: string
                startDateTime: string
                endDateTime: string
                hint: string
                secretText: string
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerCredentialDto'
              example:
                keyId: string
                displayName: string
                startDateTime: string
                endDateTime: string
                hint: string
                secretText: string
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
    post:
      tags:
      - Partners
      summary: /credentials - POST
      operationId: post-credentials
      parameters:
      - name: x-idempotency-key
        in: header
        description: Unique request idenitfier for idempotency.
        required: true
        schema:
          type: string
          format: uuid
        example: d5812a08-a251-4bc3-98e2-3d5d54dd468c
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.AddPartnerCredentialDto'
            example:
              displayName: string
              startDateTime: string
              endDateTime: string
          text/json:
            schema:
              $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.AddPartnerCredentialDto'
            example:
              displayName: string
              startDateTime: string
              endDateTime: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.AddPartnerCredentialDto'
            example:
              displayName: string
              startDateTime: string
              endDateTime: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerCredentialDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerCredentialDto'
              example:
                keyId: string
                displayName: string
                startDateTime: string
                endDateTime: string
                hint: string
                secretText: string
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerCredentialDto'
              example:
                keyId: string
                displayName: string
                startDateTime: string
                endDateTime: string
                hint: string
                secretText: string
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /credentials/{id}:
    delete:
      tags:
      - Partners
      summary: /credentials/{id} - DELETE
      operationId: delete-credentials-id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '204':
          description: No Content
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /auth-settings:
    get:
      tags:
      - Partners
      summary: /auth-settings - GET
      operationId: get-auth-settings
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerAuthSettingsDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerAuthSettingsDto'
              example:
                isSyncEnabled: true
                authProvider: string
                isAuth0ClientCredentialsEnabled: true
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerAuthSettingsDto'
              example:
                isSyncEnabled: true
                authProvider: string
                isAuth0ClientCredentialsEnabled: true
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
components:
  schemas:
    Cubi.Partners.WebApi.Dtos.AddPartnerCredentialDto:
      type: object
      properties:
        displayName:
          type:
          - string
          - 'null'
        startDateTime:
          type:
          - string
          - 'null'
          format: date-time
        endDateTime:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    Cubi.Partners.WebApi.Dtos.PartnerCredentialDto:
      type: object
      properties:
        keyId:
          type: string
          format: uuid
        displayName:
          type:
          - string
          - 'null'
        startDateTime:
          type: string
          format: date-time
        endDateTime:
          type: string
          format: date-time
        hint:
          type:
          - string
          - 'null'
        secretText:
          type:
          - string
          - 'null'
      additionalProperties: false
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        traceId:
          type:
          - string
          - 'null'
      additionalProperties: {}
    Microsoft.AspNetCore.Mvc.ValidationProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        traceId:
          type:
          - string
          - 'null'
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      additionalProperties: {}
    Cubi.Partners.WebApi.Dtos.PartnerApiProductDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        isEnabled:
          type: boolean
      additionalProperties: false
    Cubi.Partners.WebApi.Dtos.PartnerDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        isFrozen:
          type: boolean
        apiProducts:
          type: array
          items:
            $ref: '#/components/schemas/Cubi.Partners.WebApi.Dtos.PartnerApiProductDto'
        isApiCredentialsEnabled:
          type: boolean
        isAddressBookEnabled:
          type: boolean
      additionalProperties: false
    Cubi.Partners.WebApi.Dtos.PartnerAuthSettingsDto:
      type: object
      properties:
        isSyncEnabled:
          type: boolean
        authProvider:
          type:
          - string
          - 'null'
        isAuth0ClientCredentialsEnabled:
          type: boolean
      additionalProperties: false
x-readme:
  explorer-enabled: false
  proxy-enabled: true
