openapi: 3.2.0
info:
  title: IT Operations Banks API
  version: v1
servers:
- url: https://cubi-sandbox-api.customersbank.com/itoperations/v1
tags:
- name: Banks
paths:
  /Banks:
    get:
      tags:
      - Banks
      summary: /Banks - GET
      description: Searches for banks
      operationId: get-banks
      parameters:
      - name: bankName
        in: query
        description: The name of the bank for which to search
        schema:
          type: string
          example: Customers
        example: Customers
      - name: routingCode
        in: query
        description: The routing code to search for.  Can be an ABA, BIC/Swift, or any other international routing code
        schema:
          type: string
          example: '123456789'
        example: 123456789
      - name: routingType
        in: query
        description: The routing code type to search for (eg. BIC, ABA, etc.)
        schema:
          type: string
          example: ABA
        example: ABA
      - name: countryCode
        in: query
        description: The country code to search for
        schema:
          type: string
          example: US
        example: US
      - name: paginateResults
        in: query
        schema:
          type: boolean
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: perPage
        in: query
        schema:
          type: integer
          format: int32
      - name: sortOn
        in: query
        schema:
          type: string
      - name: sortAscending
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BankDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BankDto'
              example:
                pageSize: 0
                pageOffset: 0
                totalPages: 0
                totalItemCount: 0
                items:
                - locationId: 0
                  bankName: string
                  routingCode: string
                  alternateRoutingCode: string
                  routingType: string
                  pairedBic: string
                  countryCode: string
                  branchName: string
                  streetAddress: string
                  stateOrProvince: string
                  postalCode: string
                  city: string
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BankDto'
              example:
                pageSize: 0
                pageOffset: 0
                totalPages: 0
                totalItemCount: 0
                items:
                - locationId: 0
                  bankName: string
                  routingCode: string
                  alternateRoutingCode: string
                  routingType: string
                  pairedBic: string
                  countryCode: string
                  branchName: string
                  streetAddress: string
                  stateOrProvince: string
                  postalCode: string
                  city: string
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /Banks/{id}:
    get:
      tags:
      - Banks
      summary: /Banks/{id} - GET
      description: Retrieves a specific bank, by locationId
      operationId: get-banks-id
      parameters:
      - name: id
        in: path
        description: The locationId of the bank to retrieve
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BankDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BankDto'
              example:
                locationId: 0
                bankName: string
                routingCode: string
                alternateRoutingCode: string
                routingType: string
                pairedBic: string
                countryCode: string
                branchName: string
                streetAddress: string
                stateOrProvince: string
                postalCode: string
                city: string
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BankDto'
              example:
                locationId: 0
                bankName: string
                routingCode: string
                alternateRoutingCode: string
                routingType: string
                pairedBic: string
                countryCode: string
                branchName: string
                streetAddress: string
                stateOrProvince: string
                postalCode: string
                city: string
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /Banks/aba/{abaNumber}:
    get:
      tags:
      - Banks
      summary: /Banks/aba/{abaNumber} - GET
      description: Retrieves a single ABA record, by ABA
      operationId: get-banks-aba-abanumber
      parameters:
      - name: abaNumber
        in: path
        description: The ABA to retrieve
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.AbaDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.AbaDto'
              example:
                locationId: 0
                bankName: string
                abaNumber: string
                bic: string
                isWireEnabled: true
                isAchEnabled: true
                isFedNowEnabled: true
                isRTPEnabled: true
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.AbaDto'
              example:
                locationId: 0
                bankName: string
                abaNumber: string
                bic: string
                isWireEnabled: true
                isAchEnabled: true
                isFedNowEnabled: true
                isRTPEnabled: true
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /Banks/bic/{bic}:
    get:
      tags:
      - Banks
      summary: /Banks/bic/{bic} - GET
      description: Retrieves a single BIC record, by BIC
      operationId: get-banks-bic-bic
      parameters:
      - name: bic
        in: path
        description: The BIC to retrieve
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BicDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BicDto'
              example:
                locationId: 0
                bankName: string
                bic: string
                alternateBic: string
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BicDto'
              example:
                locationId: 0
                bankName: string
                bic: string
                alternateBic: string
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /Banks/aba:
    get:
      tags:
      - Banks
      summary: /Banks/aba - GET
      description: Searches all ABA records
      operationId: get-banks-aba
      parameters:
      - name: paginateResults
        in: query
        schema:
          type: boolean
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: perPage
        in: query
        schema:
          type: integer
          format: int32
      - name: sortOn
        in: query
        schema:
          type: string
      - name: sortAscending
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.AbaDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.AbaDto'
              example:
                pageSize: 0
                pageOffset: 0
                totalPages: 0
                totalItemCount: 0
                items:
                - locationId: 0
                  bankName: string
                  abaNumber: string
                  bic: string
                  isWireEnabled: true
                  isAchEnabled: true
                  isFedNowEnabled: true
                  isRTPEnabled: true
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.AbaDto'
              example:
                pageSize: 0
                pageOffset: 0
                totalPages: 0
                totalItemCount: 0
                items:
                - locationId: 0
                  bankName: string
                  abaNumber: string
                  bic: string
                  isWireEnabled: true
                  isAchEnabled: true
                  isFedNowEnabled: true
                  isRTPEnabled: true
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
  /Banks/bic:
    get:
      tags:
      - Banks
      summary: /Banks/bic - GET
      description: Searches all BIC records
      operationId: get-banks-bic
      parameters:
      - name: paginateResults
        in: query
        schema:
          type: boolean
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      - name: perPage
        in: query
        schema:
          type: integer
          format: int32
      - name: sortOn
        in: query
        schema:
          type: string
      - name: sortAscending
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BicDto'
              examples:
                default:
                  value: null
            application/json:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BicDto'
              example:
                pageSize: 0
                pageOffset: 0
                totalPages: 0
                totalItemCount: 0
                items:
                - locationId: 0
                  bankName: string
                  bic: string
                  alternateBic: string
            text/json:
              schema:
                $ref: '#/components/schemas/Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BicDto'
              example:
                pageSize: 0
                pageOffset: 0
                totalPages: 0
                totalItemCount: 0
                items:
                - locationId: 0
                  bankName: string
                  bic: string
                  alternateBic: string
        '400':
          description: BadRequest
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred.
                status: 400
                traceId: string
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: string
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: string
        '404':
          description: NotFound
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                traceId: string
        '422':
          description: UnprocessableEntity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc4918#section-11.2
                title: Unprocessable Entity
                status: 422
                traceId: string
        '500':
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.6.1
                title: An error occurred while processing your request.
                status: 500
                traceId: string
components:
  schemas:
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        traceId:
          type:
          - string
          - 'null'
      additionalProperties: {}
    Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BankDto:
      type: object
      properties:
        pageSize:
          type: integer
          format: int32
        pageOffset:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalItemCount:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BankDto'
      additionalProperties: false
    Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.AbaDto:
      type: object
      properties:
        pageSize:
          type: integer
          format: int32
        pageOffset:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalItemCount:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.AbaDto'
      additionalProperties: false
    Cubi.ITOperations.WebApi.Dto.AbaDto:
      type: object
      properties:
        locationId:
          type: integer
          description: The LocationId of the bank
          format: int32
        bankName:
          type:
          - string
          - 'null'
          description: The name of the bank
        abaNumber:
          type:
          - string
          - 'null'
          description: The ABA number of the bank
        bic:
          type:
          - string
          - 'null'
          description: The BIC for the bank
        isWireEnabled:
          type: boolean
          description: True if this ABA supports direct wires; false otherwise
        isAchEnabled:
          type: boolean
          description: True if this ABA supports direct ACH; false otherwise
        isFedNowEnabled:
          type:
          - boolean
          - 'null'
          description: True if this ABA supports FedNow; false otherwise
        isRTPEnabled:
          type:
          - boolean
          - 'null'
          description: True if this ABA supports RTP; false otherwise
      additionalProperties: false
    Microsoft.AspNetCore.Mvc.ValidationProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        traceId:
          type:
          - string
          - 'null'
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      additionalProperties: {}
    Cubi.Common.Abstractions.Paginated_Cubi.ITOperations.WebApi.Dto.BicDto:
      type: object
      properties:
        pageSize:
          type: integer
          format: int32
        pageOffset:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        totalItemCount:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/Cubi.ITOperations.WebApi.Dto.BicDto'
      additionalProperties: false
    Cubi.ITOperations.WebApi.Dto.BankDto:
      type: object
      properties:
        locationId:
          type: integer
          description: The location id of the bank
          format: int32
        bankName:
          type:
          - string
          - 'null'
          description: The name of the bank
        routingCode:
          type:
          - string
          - 'null'
          description: The routing code of the bank (could be ABA, BIC, or any international routing code)
        alternateRoutingCode:
          type:
          - string
          - 'null'
          description: The alternate routing code of the bank (could be ABA, BIC, SWIFT, or any international routing code).
        routingType:
          type:
          - string
          - 'null'
          description: The type of routing code (eg. ABA, BIC, etc.)
        pairedBic:
          type:
          - string
          - 'null'
          description: The BIC for the bank
        countryCode:
          type:
          - string
          - 'null'
          description: The two character country code for this bank location
        branchName:
          type:
          - string
          - 'null'
          description: The name of the bank branch
        streetAddress:
          type:
          - string
          - 'null'
          description: The street address of the bank location
        stateOrProvince:
          type:
          - string
          - 'null'
          description: The state/province for the bank location
        postalCode:
          type:
          - string
          - 'null'
          description: The postal code for the bank location
        city:
          type:
          - string
          - 'null'
          description: The city for the bank location
      additionalProperties: false
    Cubi.ITOperations.WebApi.Dto.BicDto:
      type: object
      properties:
        locationId:
          type: integer
          description: The location id for the bank
          format: int32
        bankName:
          type:
          - string
          - 'null'
          description: The name of the bank
        bic:
          type:
          - string
          - 'null'
          description: The BIC for the bank
        alternateBic:
          type:
          - string
          - 'null'
          description: The alternate BIC (BIC-8)
      additionalProperties: false
x-readme:
  explorer-enabled: false
  proxy-enabled: true
